import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 43,
    code: 'MEU_MENU_PM',
    name: 'Dashboard',
    type: 'MENU_PAGE',
    position: 0,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: '_self',
    url: '/dashboard',
    pageSlug: 'dashboard',
    parentCode: null,
    applicationCode: 'APP_IGRP_PM',
    permissions: [],
  },
    {
    id: 63,
    code: 'MEU_MENU_PM',
    name: 'Listar de Projetos',
    type: 'MENU_PAGE',
    position: 0,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: '_self',
    url: '/project',
    pageSlug: 'listar-projetos',
    parentCode: null,
    applicationCode: 'APP_IGRP_PM',
    permissions: [],
  },
    {
    id: 73,
    code: 'MEU_MENU_PM',
    name: 'Relatório  e Analise',
    type: 'MENU_PAGE',
    position: 0,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: '_self',
    url: '/report',
    pageSlug: 'relatorio-analise',
    parentCode: null,
    applicationCode: 'APP_IGRP_PM',
    permissions: [],
  },
  
];
